sonar.projectKey=student-academic-management-system
sonar.projectName=Student Academic Management System
sonar.sources=backend/src,frontend/src
sonar.tests=backend/src/tests
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info
sonar.sourceEncoding=UTF-8
